/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg14.swingciclistes.Forms;

/**
 *
 * @author infot
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lBackground = new javax.swing.JLabel();
        mbMain = new javax.swing.JMenuBar();
        mEquips = new javax.swing.JMenu();
        mCiclistes = new javax.swing.JMenu();
        mLlevar = new javax.swing.JMenu();
        mMaillots = new javax.swing.JMenu();
        mPorts = new javax.swing.JMenu();
        mEtapes = new javax.swing.JMenu();
        mEtapes1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N

        mEquips.setText("Equips");
        mbMain.add(mEquips);

        mCiclistes.setText("Ciclistes");
        mbMain.add(mCiclistes);

        mLlevar.setText("Llevar");
        mbMain.add(mLlevar);

        mMaillots.setText("Maillots");
        mbMain.add(mMaillots);

        mPorts.setText("Ports");
        mbMain.add(mPorts);

        mEtapes.setText("Etapes");
        mbMain.add(mEtapes);

        mEtapes1.setText("Exit");
        mbMain.add(mEtapes1);

        setJMenuBar(mbMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lBackground)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lBackground)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lBackground;
    private javax.swing.JMenu mCiclistes;
    private javax.swing.JMenu mEquips;
    private javax.swing.JMenu mEtapes;
    private javax.swing.JMenu mEtapes1;
    private javax.swing.JMenu mLlevar;
    private javax.swing.JMenu mMaillots;
    private javax.swing.JMenu mPorts;
    private javax.swing.JMenuBar mbMain;
    // End of variables declaration//GEN-END:variables
}
