/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cyclists.forms;

import cyclists.forms.Cyclist.AddCiclyst;
import cyclists.forms.Cyclist.DeleteCiclyst;
import cyclists.forms.Cyclist.ModifyCiclyst;
import cyclists.forms.Llevar.AddLlevar;
import cyclists.forms.Llevar.DeleteLlevar;
import cyclists.forms.Llevar.ModifyLlevar;
import cyclists.forms.Ports.AddPort;
import cyclists.forms.Ports.DeletePort;
import cyclists.forms.Ports.ModifyPort;
import cyclists.forms.Shirt.AddShirt;
import cyclists.forms.Shirt.DeleteShirt;
import cyclists.forms.Shirt.ModifyShirt;
import cyclists.forms.Stage.AddStage;
import cyclists.forms.Stage.DeleteStage;
import cyclists.forms.Stage.ModifyStage;
import cyclists.forms.Team.AddTeam;
import cyclists.forms.Team.DeleteTeam;
import cyclists.forms.Team.ModifyTeam;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author infot
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../../images/icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        lBackground = new javax.swing.JLabel();
        mbMain = new javax.swing.JMenuBar();
        mTeams = new javax.swing.JMenu();
        miAddTeams = new javax.swing.JMenuItem();
        miModifyTeams = new javax.swing.JMenuItem();
        miDeleteTeams = new javax.swing.JMenuItem();
        mCyclist = new javax.swing.JMenu();
        miAddCyclist = new javax.swing.JMenuItem();
        miModifyCyclist = new javax.swing.JMenuItem();
        miDeleteCyclist = new javax.swing.JMenuItem();
        mLlevar = new javax.swing.JMenu();
        miAddLllevar = new javax.swing.JMenuItem();
        miModifyLllevar = new javax.swing.JMenuItem();
        miDeleteLllevar = new javax.swing.JMenuItem();
        mShirt = new javax.swing.JMenu();
        miAddShirt = new javax.swing.JMenuItem();
        miModifyShirt = new javax.swing.JMenuItem();
        miDeleteShirt = new javax.swing.JMenuItem();
        mPorts = new javax.swing.JMenu();
        miAddPorts = new javax.swing.JMenuItem();
        miModifyPorts = new javax.swing.JMenuItem();
        miDeletePorts = new javax.swing.JMenuItem();
        mStages = new javax.swing.JMenu();
        miAddStage = new javax.swing.JMenuItem();
        miModifyStage = new javax.swing.JMenuItem();
        miDeleteStage = new javax.swing.JMenuItem();
        mExit = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconImages(null);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N

        mTeams.setText("Teams");

        miAddTeams.setText("Add");
        miAddTeams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddTeamsActionPerformed(evt);
            }
        });
        mTeams.add(miAddTeams);

        miModifyTeams.setText("Modify");
        miModifyTeams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miModifyTeamsActionPerformed(evt);
            }
        });
        mTeams.add(miModifyTeams);

        miDeleteTeams.setText("Delete");
        miDeleteTeams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDeleteTeamsActionPerformed(evt);
            }
        });
        mTeams.add(miDeleteTeams);

        mbMain.add(mTeams);

        mCyclist.setText("Cyclist");

        miAddCyclist.setText("Add");
        miAddCyclist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddCyclistActionPerformed(evt);
            }
        });
        mCyclist.add(miAddCyclist);

        miModifyCyclist.setText("Modify");
        miModifyCyclist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miModifyCyclistActionPerformed(evt);
            }
        });
        mCyclist.add(miModifyCyclist);

        miDeleteCyclist.setText("Delete");
        miDeleteCyclist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDeleteCyclistActionPerformed(evt);
            }
        });
        mCyclist.add(miDeleteCyclist);

        mbMain.add(mCyclist);

        mLlevar.setText("Llevar");

        miAddLllevar.setText("Add");
        miAddLllevar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddLllevarActionPerformed(evt);
            }
        });
        mLlevar.add(miAddLllevar);

        miModifyLllevar.setText("Modify");
        miModifyLllevar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miModifyLllevarActionPerformed(evt);
            }
        });
        mLlevar.add(miModifyLllevar);

        miDeleteLllevar.setText("Delete");
        miDeleteLllevar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDeleteLllevarActionPerformed(evt);
            }
        });
        mLlevar.add(miDeleteLllevar);

        mbMain.add(mLlevar);

        mShirt.setText("Shirt");

        miAddShirt.setText("Add");
        miAddShirt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddShirtActionPerformed(evt);
            }
        });
        mShirt.add(miAddShirt);

        miModifyShirt.setText("Modify");
        miModifyShirt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miModifyShirtActionPerformed(evt);
            }
        });
        mShirt.add(miModifyShirt);

        miDeleteShirt.setText("Delete");
        miDeleteShirt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDeleteShirtActionPerformed(evt);
            }
        });
        mShirt.add(miDeleteShirt);

        mbMain.add(mShirt);

        mPorts.setText("Ports");

        miAddPorts.setText("Add");
        miAddPorts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddPortsActionPerformed(evt);
            }
        });
        mPorts.add(miAddPorts);

        miModifyPorts.setText("Modify");
        miModifyPorts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miModifyPortsActionPerformed(evt);
            }
        });
        mPorts.add(miModifyPorts);

        miDeletePorts.setText("Delete");
        miDeletePorts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDeletePortsActionPerformed(evt);
            }
        });
        mPorts.add(miDeletePorts);

        mbMain.add(mPorts);

        mStages.setText("Stage");

        miAddStage.setText("Add");
        miAddStage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddStageActionPerformed(evt);
            }
        });
        mStages.add(miAddStage);

        miModifyStage.setText("Modify");
        miModifyStage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miModifyStageActionPerformed(evt);
            }
        });
        mStages.add(miModifyStage);

        miDeleteStage.setText("Delete");
        miDeleteStage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDeleteStageActionPerformed(evt);
            }
        });
        mStages.add(miDeleteStage);

        mbMain.add(mStages);

        mExit.setText("Exit");
        mExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mExitMousePressed(evt);
            }
        });
        mbMain.add(mExit);

        setJMenuBar(mbMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lBackground)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lBackground)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Function for create Alerts with Warning icon
    public static void alertsWarning(JFrame jf, String title, String message) {
        JOptionPane.showMessageDialog(jf, message, title, JOptionPane.WARNING_MESSAGE);
    }

    //Function for create Alerts with Information icon
    public static void alertsInformation(JFrame jf, String title, String message) {
        JOptionPane.showMessageDialog(jf, message, title, JOptionPane.INFORMATION_MESSAGE);
    }

    private void miAddCyclistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddCyclistActionPerformed
        // TODO add your handling code here:
        AddCiclyst ac = new AddCiclyst();
        addFrame(ac, "Add Cyclist");

        //this.setEnabled(false);
    }//GEN-LAST:event_miAddCyclistActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        exitDialog();
    }//GEN-LAST:event_formWindowClosing

    private void miDeleteCyclistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDeleteCyclistActionPerformed
        DeleteCiclyst dc = new DeleteCiclyst();
        addFrame(dc, "Delete Cyclist");
        //this.setEnabled(false);
    }//GEN-LAST:event_miDeleteCyclistActionPerformed

    public void exitDialog() {
        if (JOptionPane.showConfirmDialog(this,
                "Are you sure to close this window?", "Really Closing?",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    public static void addFrame(JFrame jf, String text) {
        jf.setTitle(text);
        jf.setLocationRelativeTo(null);
        jf.setVisible(true);
    }

    private void mExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mExitMousePressed
        // TODO add your handling code here:
        exitDialog();
    }//GEN-LAST:event_mExitMousePressed

    private void miModifyCyclistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miModifyCyclistActionPerformed
        ModifyCiclyst mc = new ModifyCiclyst();
        addFrame(mc, "Modify Cyclist");
    }//GEN-LAST:event_miModifyCyclistActionPerformed

    private void miAddTeamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddTeamsActionPerformed
        // TODO add your handling code here:
        AddTeam at = new AddTeam();
        addFrame(at, "Add Team");
    }//GEN-LAST:event_miAddTeamsActionPerformed

    private void miModifyTeamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miModifyTeamsActionPerformed
        // TODO add your handling code here:
        ModifyTeam mt = new ModifyTeam();
        addFrame(mt, "Modify Team");
    }//GEN-LAST:event_miModifyTeamsActionPerformed

    private void miDeleteTeamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDeleteTeamsActionPerformed
        // TODO add your handling code here:
        DeleteTeam dt = new DeleteTeam();
        dt.setTitle("Delete  Team");
        addFrame(dt, "Delete Team");
    }//GEN-LAST:event_miDeleteTeamsActionPerformed

    private void miAddShirtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddShirtActionPerformed
        // TODO add your handling code here:
        AddShirt as = new AddShirt();
        addFrame(as, "Add Shirt");
    }//GEN-LAST:event_miAddShirtActionPerformed

    private void miModifyShirtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miModifyShirtActionPerformed
        // TODO add your handling code here:
        ModifyShirt ms = new ModifyShirt();
        addFrame(ms, "Modify Shirt");
    }//GEN-LAST:event_miModifyShirtActionPerformed

    private void miDeleteShirtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDeleteShirtActionPerformed
        // TODO add your handling code here:
        DeleteShirt ds = new DeleteShirt();
        addFrame(ds, "Delete Shirt");
    }//GEN-LAST:event_miDeleteShirtActionPerformed

    private void miAddPortsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddPortsActionPerformed
        // TODO add your handling code here:
        AddPort ap = new AddPort();
        addFrame(ap, "Add Port");
    }//GEN-LAST:event_miAddPortsActionPerformed

    private void miModifyPortsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miModifyPortsActionPerformed
        // TODO add your handling code here:
        ModifyPort mp = new ModifyPort();
        addFrame(mp, "Modify Port");
    }//GEN-LAST:event_miModifyPortsActionPerformed

    private void miDeletePortsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDeletePortsActionPerformed
        // TODO add your handling code here:
        DeletePort dp = new DeletePort();
        addFrame(dp, "Delete Port");
    }//GEN-LAST:event_miDeletePortsActionPerformed

    private void miAddStageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddStageActionPerformed
        // TODO add your handling code here:
        AddStage as = new AddStage();
        addFrame(as, "Add Stage");
    }//GEN-LAST:event_miAddStageActionPerformed

    private void miModifyStageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miModifyStageActionPerformed
        // TODO add your handling code here:
        ModifyStage ms = new ModifyStage();
        addFrame(ms, "Modify Stage");
    }//GEN-LAST:event_miModifyStageActionPerformed

    private void miDeleteStageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDeleteStageActionPerformed
        // TODO add your handling code here:
        DeleteStage ds = new DeleteStage();
        addFrame(ds, "Delete Stage");
    }//GEN-LAST:event_miDeleteStageActionPerformed

    private void miAddLllevarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddLllevarActionPerformed
        // TODO add your handling code here:
        AddLlevar al = new AddLlevar();
        addFrame(al, "Add Llevar");
    }//GEN-LAST:event_miAddLllevarActionPerformed

    private void miModifyLllevarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miModifyLllevarActionPerformed
        // TODO add your handling code here:
        ModifyLlevar ml = new ModifyLlevar();
        addFrame(ml, "Modify Llevar");
    }//GEN-LAST:event_miModifyLllevarActionPerformed

    private void miDeleteLllevarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDeleteLllevarActionPerformed
        // TODO add your handling code here:
        DeleteLlevar dl = new DeleteLlevar();
        addFrame(dl, "Delete Llevar");
    }//GEN-LAST:event_miDeleteLllevarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel lBackground;
    private javax.swing.JMenu mCyclist;
    private javax.swing.JMenu mExit;
    private javax.swing.JMenu mLlevar;
    private javax.swing.JMenu mPorts;
    private javax.swing.JMenu mShirt;
    private javax.swing.JMenu mStages;
    private javax.swing.JMenu mTeams;
    private javax.swing.JMenuBar mbMain;
    private javax.swing.JMenuItem miAddCyclist;
    private javax.swing.JMenuItem miAddLllevar;
    private javax.swing.JMenuItem miAddPorts;
    private javax.swing.JMenuItem miAddShirt;
    private javax.swing.JMenuItem miAddStage;
    private javax.swing.JMenuItem miAddTeams;
    private javax.swing.JMenuItem miDeleteCyclist;
    private javax.swing.JMenuItem miDeleteLllevar;
    private javax.swing.JMenuItem miDeletePorts;
    private javax.swing.JMenuItem miDeleteShirt;
    private javax.swing.JMenuItem miDeleteStage;
    private javax.swing.JMenuItem miDeleteTeams;
    private javax.swing.JMenuItem miModifyCyclist;
    private javax.swing.JMenuItem miModifyLllevar;
    private javax.swing.JMenuItem miModifyPorts;
    private javax.swing.JMenuItem miModifyShirt;
    private javax.swing.JMenuItem miModifyStage;
    private javax.swing.JMenuItem miModifyTeams;
    // End of variables declaration//GEN-END:variables

}
