/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cyclists.forms.Llevar;

import cyclists.Database;
import cyclists.Entity.Ports;
import cyclists.forms.MainForm;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/**
 *
 * @author Richard
 */
public class AddPort extends javax.swing.JFrame {

    /**
     * Creates new form AddPort
     */
    public AddPort() {
        initComponents();
        try {
            //Filling the ComboBox            
            Ports p = new Ports();
            p.loadTable(pTablePort);
            p.addItemsCombo(cbStage, cbDorsal);
        } catch (SQLException ex) {
            Logger.getLogger(AddPort.class.getName()).log(Level.SEVERE, null, ex);
        }
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../../../images/icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btInsert = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbStage = new javax.swing.JComboBox<>();
        pTablePort = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cbDorsal = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbStage1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btInsert.setText("Insert");
        btInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsertActionPerformed(evt);
            }
        });

        jLabel2.setText("New Port");

        jLabel3.setText("Shirt ID");

        cbStage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        cbStage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStageActionPerformed(evt);
            }
        });

        pTablePort.setMaximumSize(new java.awt.Dimension(32767, 234));

        javax.swing.GroupLayout pTablePortLayout = new javax.swing.GroupLayout(pTablePort);
        pTablePort.setLayout(pTablePortLayout);
        pTablePortLayout.setHorizontalGroup(
            pTablePortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );
        pTablePortLayout.setVerticalGroup(
            pTablePortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel7.setText("Cyclist Dorsal");

        cbDorsal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        jLabel8.setText("Stage Num");

        cbStage1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        cbStage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStage1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btInsert))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbDorsal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel3))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbStage, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbStage1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(pTablePort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pTablePort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(10, 10, 10))
                            .addComponent(cbDorsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cbStage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addComponent(btInsert)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsertActionPerformed
        // TODO add your handling code here:
        // tfAlerts
        if (tfName.getText().isEmpty() && tfHeight.getText().isEmpty() && tfCategory.getText().isEmpty() && tfSlope.getText().isEmpty()) {
            MainForm.alertsWarning(this, "All values missing", "Name, height, category and slope fields are missing");
            tfName.requestFocus();
        } else if (tfName.getText().isEmpty() && tfHeight.getText().isEmpty() && tfCategory.getText().isEmpty()) {
            MainForm.alertsWarning(this, "Fields missing", "Name, height and category fields are missing");
            tfName.requestFocus();
        } else if (tfName.getText().isEmpty() && tfHeight.getText().isEmpty() && tfSlope.getText().isEmpty()) {
            MainForm.alertsWarning(this, "Fields missing", "Name, height and slope fields are missing");
            tfName.requestFocus();
        } else if (tfName.getText().isEmpty() && tfCategory.getText().isEmpty() && tfSlope.getText().isEmpty()) {
            MainForm.alertsWarning(this, "Fields missing", "Name, category and slope fields are missing");
            tfName.requestFocus();
        } else if (tfHeight.getText().isEmpty() && tfCategory.getText().isEmpty() && tfSlope.getText().isEmpty()) {
            MainForm.alertsWarning(this, "Fields missing", "Height, category and slope fields are missing");
        } else if (tfName.getText().isEmpty() && tfCategory.getText().isEmpty()) {
            MainForm.alertsWarning(this, "Fields missing", "Name and category fields are missing");
            tfName.requestFocus();
        } else if (tfName.getText().isEmpty() && tfHeight.getText().isEmpty()) {
            MainForm.alertsWarning(this, "Fields missing", "Name and height fields are missing");
            tfName.requestFocus();
        } else if (tfName.getText().isEmpty() && tfSlope.getText().isEmpty()) {
            MainForm.alertsWarning(this, "Fields missing", "Name and slope fields are missing");
            tfName.requestFocus();
        } else if (tfCategory.getText().isEmpty() && tfName.getText().isEmpty()) {
            MainForm.alertsWarning(this, "Fields missing", "Category and name fields are missing");
            tfName.requestFocus();
        } else if (tfCategory.getText().isEmpty() && tfHeight.getText().isEmpty()) {
            MainForm.alertsWarning(this, "Fields missing", "Category and height fields are missing");
            tfHeight.requestFocus();
        } else if (tfCategory.getText().isEmpty() && tfSlope.getText().isEmpty()) {
            MainForm.alertsWarning(this, "Fields missing", "Category and slope fields are missing");
            tfCategory.requestFocus();
        } else if (tfHeight.getText().isEmpty() && tfName.getText().isEmpty()) {
            MainForm.alertsWarning(this, "Fields missing", "Height and name fields are missing");
            tfName.requestFocus();
        } else if (tfHeight.getText().isEmpty() && tfCategory.getText().isEmpty()) {
            MainForm.alertsWarning(this, "Fields missing", "Height and category fields are missing");
            tfHeight.requestFocus();
        } else if (tfHeight.getText().isEmpty() && tfSlope.getText().isEmpty()) {
            MainForm.alertsWarning(this, "Fields missing", "Height and slope fields are missing");
            tfHeight.requestFocus();
        } else if (tfSlope.getText().isEmpty() && tfName.getText().isEmpty()) {
            MainForm.alertsWarning(this, "Fields missing", "Slope and name fields are missing");
            tfName.requestFocus();
        } else if (tfSlope.getText().isEmpty() && tfCategory.getText().isEmpty()) {
            MainForm.alertsWarning(this, "Fields missing", "Slope and category fields are missing");
            tfCategory.requestFocus();
        } else if (tfSlope.getText().isEmpty() && tfHeight.getText().isEmpty()) {
            MainForm.alertsWarning(this, "Fields missing", "Slope and height fields are missing");
            tfHeight.requestFocus();
        } else if (tfName.getText().isEmpty()) {
            MainForm.alertsWarning(this, "Field missing", "Name is missing");
            tfName.requestFocus();
        } else if (tfHeight.getText().isEmpty()) {
            MainForm.alertsWarning(this, "Field missing", "Height is missing");
            tfHeight.requestFocus();
        } else if (tfSlope.getText().isEmpty()) {
            MainForm.alertsWarning(this, "Field missing", "Slope is missing");
            tfSlope.requestFocus();
        } else if (tfCategory.getText().isEmpty()) {
            MainForm.alertsWarning(this, "Field missing", "Category is missing");
            tfCategory.requestFocus();
        } else {
            String name = tfName.getText();
            int height = Integer.parseInt(tfHeight.getText());
            String category = tfCategory.getText();
            double slope = Double.parseDouble(tfSlope.getText());
            int stage = Integer.parseInt(cbStage.getSelectedItem().toString());
            int dorsal = Integer.parseInt(cbDorsal.getSelectedItem().toString());

            Database db = new Database();
            try {
                if (db.searchID("nomport", "Ports", name)) {
                    MainForm.alertsWarning(this, "ID Duplicated", "ID Duplicated");
                    // putting focus on tfDorsal
                    tfName.requestFocus();
                } else {
                    // Insert
                    String sqlInsert = "INSERT INTO Ports VALUES(?,?,?,?,?,?)";

                    //Connect
                    db.makeConnection();

                    PreparedStatement pst = db.getConnection().prepareStatement(sqlInsert);
                    pst.setString(1, name);
                    pst.setInt(2, height);
                    pst.setString(3, category);
                    pst.setDouble(4, slope);
                    pst.setInt(5, stage);
                    pst.setInt(6, dorsal);

                    pst.execute();
                    //Disconnect
                    db.closeConnection();
                    //End of Insert
                    //Information Message
                    MainForm.alertsInformation(this, "Row inserted", "Row inserted");
                    //The actual frame close
                    this.setVisible(false);
                }
            } catch (SQLException ex) {
                Logger.getLogger(AddPort.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btInsertActionPerformed


    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setVisible(false);
//        this.rootPane.setEnabled(true);
//        this.rootPane.requestFocus();
    }//GEN-LAST:event_formWindowClosing

    private void cbStageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStageActionPerformed

    private void cbStage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStage1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStage1ActionPerformed

    private void consumeEvente(KeyEvent evt, JTextField tf, int max) {
        char c = evt.getKeyChar();
        if (tf.getText().length() > max) {
            evt.consume();
        }
        if (((c < '0') || (c > '9')) && (c != '\b')) {
            evt.consume();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPort().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btInsert;
    private javax.swing.JComboBox<String> cbDorsal;
    private javax.swing.JComboBox<String> cbStage;
    private javax.swing.JComboBox<String> cbStage1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel pTablePort;
    // End of variables declaration//GEN-END:variables
}
